version: "3.8"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - 6333:6333
      - 8501:8501

    volumes:
      - .:/app

    environment:
      - TOGETHER_API_KEY= ${TOGETHER_API_KEY}
      - SERPAPI_API_KEY=${SERPAPI_API_KEY}
      - ASTRA_DB_TOKEN=${ASTRA_DB_TOKEN}
      - ASTRA_DB_API_ENDPOINT= ${ASTRA_DB_API_ENDPOINT}
    
    develop:
      watch:
        - path: .
          action: rebuild

    deploy:
      resources:
        limits:
          memory: 4096M  # Adjust the memory limit as needed
